# Generated by Django 3.2.5 on 2021-08-08 23:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=0, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pictures/%Y/%m'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default=0, max_length=255, verbose_name='nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default=0, max_length=255, verbose_name='sobrenome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default=0, max_length=14, verbose_name='telefone'),
            preserve_default=False,
        ),
    ]
