# Generated by Django 3.2.5 on 2021-07-25 22:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cat', models.CharField(blank=True, max_length=55, null=True, verbose_name='nome_categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='sobrenome')),
                ('telefone', models.CharField(max_length=14, verbose_name='telefone')),
                ('data_nascimento', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, upload_to='pictures/%Y/%m')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contatos.categoria')),
            ],
        ),
    ]
