# Generated by Django 3.2.5 on 2021-07-25 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contato',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
    ]
